### PR TITLE
Use standard unit prefixes

### PR DESCRIPTION
**Pull request by tatref**

### CODE REVIEW

**Comment by tatref** [comment]
`m` is the prefix for milli, `M` is for mega. Graph software like pnp4nagios might missunderstand the units and insert 0.001 in the graph database, instead of the actuel value 1000 for example.

I also updated the readme, travis, and the help message in the script itself.

**Comment by timdaman** [comment]
Sweet, great catch! Thank you for the patch. One minor detail though, I think it will break the user interface. For example, if a user previously used check_docker with a unit specifier, say 'm',  their command will be broken since that is no longer a valid unit, it is now 'M'. 

The best way I can see to preserve the user interface is by creating a translation table when printing the unit. Is there a better strategy you can think of?

**Comment by tatref** [comment]
Yes it will break the inputs. Maybe we could ingore the case?

Note that it will also break the graph in the sense that the values will bump by a factor of 1.000.000, one will probably see the previous values as ~0.

**Comment by timdaman** [comment]
Sorry for the slow reply. I agree with your point. Hmm. I an inclined to make the change as the currently output is technically broken/inaccurate output. I am fine ignoring case but that won't be a complete fix. According to the doc I could find, https://www.monitoring-plugins.org/doc/guidelines.html#AEN201, data units should be one of B, KB, MB, or TB. We will need a translation table anyhow. 

        {
            "b": "B",
            "k": "KB",
            "kb": "KB",
            "m": "MB",
            "mb": "MB",
            "g": "GB",
            "gb": "GB",
            "tb": "TB",
            "t": "TB",
        }

**Comment by tatref** [comment]
This seems fine, I will try to take a look at this.

**Comment by timdaman** [comment]
Hi, I didn't forget about you. I had held off merging because of API breakage and also failing tests but I am prepping for a major revision so I would like to incorporate your improvements as part of that.

My work on the 2.0 release is being done here. I would appreciate any input.
https://github.com/timdaman/check_docker/tree/prep_for_v2

**Comment by tatref** [comment]
Hi,

I did had much time to work on this, but I'll gladly test your WIP for v2 on my infrastructure, and help to merge my proposed changes!

**Comment by timdaman** [comment]
I have updated the list of acceptable units an pushed that change to my prep_for_v2 branch if you want to take a peek.

**Comment by tatref** [comment]
Hi,

This seems fine, I'll test it on monday on a couple of servers.

**Comment by tatref** [comment]
So, I took a look at the updated code. I'm not sure if you want to keep the comments here, or maybe we should open a separate issue for v2?

- running the script without option prints a not so useful stacktrace:
```
  File "check_docker", line 739, in <module>
    perform_checks(argv[1:])
  File "check_docker", line 685, in perform_checks
    args = process_args(raw_args)
  File "check_docker", line 636, in process_args
    parser.print_help()
  File "/usr/lib64/python3.4/argparse.py", line 2359, in print_help
    self._print_message(self.format_help(), file)
  File "/usr/lib64/python3.4/argparse.py", line 2343, in format_help
    return formatter.format_help()
  File "/usr/lib64/python3.4/argparse.py", line 278, in format_help
    help = self._root_section.format_help()
  File "/usr/lib64/python3.4/argparse.py", line 208, in format_help
    func(*args)
  File "/usr/lib64/python3.4/argparse.py", line 208, in format_help
    func(*args)
  File "/usr/lib64/python3.4/argparse.py", line 515, in _format_action
    help_text = self._expand_help(action)
  File "/usr/lib64/python3.4/argparse.py", line 602, in _expand_help
    return self._get_help_string(action) % params
ValueError: unsupported format character ',' (0x2c) at index 79
```

- the units conversions are not correct: you are using 1024 base, but displaying `MB`, this should be `MiB`. Or else, use 1000 base?

- I tested the memory, cpu and status on docker-ce 17.09, everything works fine!

- one last suggestion: maybe you could round the values displayed in the text output (not perfdata). In `evaluate_numeric_thresholds`, I changed the display code to:

```
    if greater_than:
        if value >= crit:
            critical("{} {} is {}{}".format(container, name, round(value, 2), units))
        elif value >= warn:
            warning("{} {} is {}{}".format(container, name, round(value, 2), units))
        else:
            ok("{} {} is {}{}".format(container, name, round(value, 2), units))
    else:
        if value <= crit:
            critical("{} {} is {}{}".format(container, name, round(value, 2), units))
        elif value <= warn:
            warning("{} {} is {}{}".format(container, name, round(value, 2), units))
        else:
            ok("{} {} is {}{}".format(container, name, round(value, 2), units))
```

Here is the difference:
`CRITICAL: dev-piwik-web memory is 180.7265625MB|dev-piwik-web_mem=180.7265625MB;20;30;0;992.6015625`

vs

`CRITICAL: dev-piwik-web memory is 180.73MB|dev-piwik-web_mem=180.7265625MB;20;30;0;992.6015625`

**Comment by timdaman** [comment]
Good catch with the exception. Took me a bit to figure it out. It was the 'unescaped' % in the help text for memory. I have fixed in on my laptop but I want to rework the test suite before I push it so it may be a few days.

As for the units I agree about moving this to an issue. 
https://github.com/timdaman/check_docker/issues/28

I totally agree about the rounding. I just hadn't gotten to that yet with all the other things I am working on in this release. I have shameless stolen your sample code and put in my working branch.

Thank you for such great feedback!

**Comment by timdaman** [comment]
Closing as this improvement is part of the 2.0.0 release.

**Pull request closed without merging**
